### ISSUE TITLE
Add limit for tag name - 30

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#1102] opened 2024-06-18 04:11 UTC

**Comment by tritonJS826** [comment] 2024-06-18 04:12
done on the back

**Comment by Ekaterina1994** [comment] 2024-06-18 09:15
Diplicate of #973 / Need more details - need limit for tag or labels and etc.

**Comment by tritonJS826** [comment] 2024-06-18 21:58
Yeah right - need visual limit on the frontend 30 chars for label in the modal

**Comment by tritonJS826** [comment] 2024-06-18 22:00
duplicate of #973

**Comment by EkaterinaSokolova-V** [comment] 2024-06-20 17:35
It is impossible to create a tag with a name longer than 30 characters. 
However, it is necessary to inform the user that they have entered an unsupported number of characters while assigning the name. Currently, any number of characters can be entered, and only after clicking 'OK' does the error message appear.

**Comment by Ekaterina1994** [comment] 2024-06-20 18:47
@EkaterinaSokolova-V As was mentioned it's a duplicate of #973. Should be closed

**Closed** 2024-06-20 21:00 UTC
Labels: feature, p3
