### ISSUE TITLE
Create method for copy way

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#757] opened 2024-04-24 16:11 UTC

**Comment by tritonJS826** [comment] 2024-05-12 23:58
duplicate of #736

**Comment by pp2amd6** [comment] 2024-05-14 17:01
Copying way not work correctly:
- #751 reproduced
- #736 reproduced

**Comment by tritonJS826** [comment] 2024-05-14 20:26
it is duplicate, will be fixed in #736

**Closed** 2024-05-15 10:47 UTC
Labels: feature, p1
