### ISSUE TITLE
Labels not copied when user use "repeat the way" action

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#751] opened 2024-04-24 11:11 UTC
Metrics also not copied

**Comment by tritonJS826** [comment] 2024-05-12 22:44
duplicate of #736

**Comment by pp2amd6** [comment] 2024-05-14 16:59
Still reproduce

**Comment by Ekaterina1994** [comment] 2024-05-26 08:02
Duplicate of #736. Will be fixed in issue #736

**Comment by pp2amd6** [comment] 2024-05-27 18:39
Closed as duplicate

**Closed by pp2amd6** 2024-05-27 18:39 UTC
Labels: bug, p1
