### ISSUE TITLE
About project page: Links texts blend into the background and aren't visible in FAQ section

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1160] opened 2024-06-21 19:54 UTC
Preconditions
About project page is opened

Steps
1.	Click on questions "How can you cooperate with us?", "How to fill the way correctly?", "How do you leave feedback?", "How do I install an app on my phone?" and "I like your project, how can I help you?" to reveal the content associated with them
2.	Scroll and find out invisible links

Expected result
All link texts are visible

Actual result
Next links are invisible because they blend into the background:
victorveretennikov58@gmail.com (3 times)
www.linkedin.com/in/victor-veretennikov
Here 
PWA technology
android
iphone/ipad
windows

https://github.com/tritonJS826/masters-way/assets/163824877/2effa604-54b6-4845-96f2-acb81310dd2e

**Comment by vikpak89** [comment] 2024-07-05 17:09
https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=408-4243&t=tERfHRrHWvCrb68p-1

**Comment by Ekaterina1994** [comment] 2024-07-08 13:26
Duplicate of #1126

**Closed by Ekaterina1994** 2024-07-08 13:26 UTC
Labels: bug
